### ISSUE TITLE
Further feedback on code structure

### ISSUE THREAD

**Issue by Emily-Jiang** [majguo/liberty-aad-oidc#2] opened 2020-06-02 17:20 UTC
- Run against Java 11

I checked out your gitrepo and tried to build with Java 11. However it failed because jaxb was deleted from JDK11. I added the following 
<dependency>
                <groupId>javax.xml.bind</groupId>
                <artifactId>jaxb-api</artifactId>
                <version>2.3.1</version>
                
            </dependency>
            <dependency>
                <groupId>com.sun.xml.bind</groupId>
                <artifactId>jaxb-core</artifactId>
                <version>2.3.0.1</version>
                
            </dependency>
            <dependency>
                <groupId>com.sun.xml.bind</groupId>
                <artifactId>jaxb-impl</artifactId>
                <version>2.3.2</version>   
            </dependency>

- I changed the pom.xml to add liberty maven plugin so that you can start your app when running mvn clean package

	<properties>
		<openliberty.version>[20.0.0.1,)</openliberty.version>
		<openliberty.maven.version>3.2</openliberty.maven.version>
	</properties>
<plugin>
            <groupId>io.openliberty.tools</groupId>
            <artifactId>liberty-maven-plugin</artifactId>
            <version>${openliberty.maven.version}</version>
            <executions>
              <execution>
                <id>package-server</id>
                <phase>package</phase>
                <goals>
                  <goal>create</goal>
                  <goal>install-feature</goal>
                  <goal>deploy</goal>
                  <goal>package</goal>
                </goals>
                <configuration>
                  <outputDirectory>target/wlp-package</outputDirectory>
                </configuration>
              </execution>
            </executions>
            
          </plugin>
You can even do `mvn liberty:dev` to start you app in dev mode so that you can watch the changes as you code along.
I also moved server.xml from the root to src/main and then under liberty/config so that the server.xml can be picked up automatically. I think it is neater that. You can config the location to server.xml if you like. See [here](https://github.com/OpenLiberty/ci.maven) for more info.

- server.xml
At the moment, you packaged javaee-8.0, which is the full Java EE8 stack. Liberty is composable. It will only load the necessary runtime based on your server.xml. I have trimmed down your server.xml to the necessary features so that the runtime is much smaller.

<featureManager>
		<feature>cdi-2.0</feature>
		<feature>jaxb-2.2</feature>
		<feature>jpa-2.2</feature>
		<feature>jsf-2.3</feature>
		<feature>jaxrs-2.1</feature>
		<feature>ejbLite-3.2</feature>
		<feature>openidConnectClient-1.0</feature>
		<feature>transportSecurity-1.0</feature>
		<feature>appSecurity-2.0</feature>
	</featureManager>

By the way, I have not set up all the necessary credentials, so I did not do the full test. Please try the suggestions out to see whether you hit any issues.

**Comment by majguo** [comment] 2020-06-04 12:00
Thanks for the comments. The issue is fixed in https://github.com/majguo/liberty-aad-oidc/pull/5.

**Comment by majguo** [comment] 2020-06-23 10:11
Closing the issue as it's already fixed in #5.

**Closed as completed** 2020-06-23 10:11 UTC
